<?php
${"GLOBALS"}["yyklgan"]="level";
${"GLOBALS"}["qdkgtlcvis"]="reward";
${"GLOBALS"}["tippmypkcnsk"]="jsvideo";
${"GLOBALS"}["iweeglfe"]="jsmilstone2";
${"GLOBALS"}["vbnxkoj"]="jsmilstone";
${"GLOBALS"}["mreqlewgnex"]="code";
${"GLOBALS"}["rnuwrmn"]="vipcekin";
${"GLOBALS"}["mkiaed"]="msg";
${"GLOBALS"}["lxxskbiyve"]="jsabsen";
${"GLOBALS"}["lweybhsv"]="js";
${"GLOBALS"}["knxppshtusj"]="red";
${"GLOBALS"}["ctmppqek"]="cpoin";
${"GLOBALS"}["ppqgmwytr"]="login";
${"GLOBALS"}["efanrdqbddde"]="nik";
${"GLOBALS"}["rmyhfvcr"]="uid";
${"GLOBALS"}["flrpdukdcr"]="token";
${"GLOBALS"}["xqezyist"]="i";
${"GLOBALS"}["akqxqpixx"]="poin";
${"GLOBALS"}["jwvjlsowe"]="head";
${"GLOBALS"}["ccwyfzx"]="config";
${"GLOBALS"}["mwmsohiueyu"]="i";
${"GLOBALS"}["nhuosqbh"]="delay";
${"GLOBALS"}["jfsosncjc"]="akun";
${"GLOBALS"}["kxjnvj"]="x";
${"GLOBALS"}["efecvqjgmx"]="t";
${"GLOBALS"}["qtqlqvxz"]="turkis";
$ldlyvpwosoch="t";
${"GLOBALS"}["vysmmmbxeadg"]="putih";
${"GLOBALS"}["niczhiir"]="t";
$psamojfi="i";
${"GLOBALS"}["mlhvfsqvhbk"]="kuning";
${"GLOBALS"}["qpqgnnywsbk"]="putih";
$wulpluf="i";
${"GLOBALS"}["dabpkwhbo"]="i";
$jcbmgsecun="t";
$tnbvyo="ijo";
${"GLOBALS"}["hfzywfu"]="pink";
${"GLOBALS"}["sxmwlsml"]="x";
${"GLOBALS"}["bccucg"]="akun";
${"GLOBALS"}["dmqkjyjkti"]="i";
${"GLOBALS"}["ewoymbpit"]="putih";
${"GLOBALS"}["zuupeplpj"]="ijo";
$kvlbwkx="msgveeu";
${"GLOBALS"}["bfmephuwrq"]="biru";
$fcfdljgfgepl="t";
date_default_timezone_set("Asia/Jakarta");
$arpewquwd="ijo";
$owtwpesdwu="i";
@system("clear");
$yetdzspdmkb="akun";
@system("rm -rf user");
${"GLOBALS"}["juhnhqyepn"]="t";
${"GLOBALS"}["ulvmnkrhxe"]="turkis";
@system("git clone https://github.com/traidun90/user");
${"GLOBALS"}["vthdbfi"]="i";
$efuyzznnn="ijo";
${"GLOBALS"}["xcwsot"]="red";
@system("clear");
${${"GLOBALS"}["bfmephuwrq"]}="\033[1;34m";
${${"GLOBALS"}["ulvmnkrhxe"]}="\033[1;36m";
${${"GLOBALS"}["zuupeplpj"]}="\033[92m";
${"GLOBALS"}["hoibcucbgb"]="i";
${${"GLOBALS"}["ewoymbpit"]}="\033[1;37m";
${"GLOBALS"}["qbpusmciylx"]="t";
$tjttcpzfg="turkis";
${"GLOBALS"}["jeyuamxdfwzu"]="t";
$yslboabukz="config";
${${"GLOBALS"}["hfzywfu"]}="\033[1;35m";
${${"GLOBALS"}["xcwsot"]}="\033[1;31m";
$pxlrknu="i";
${${"GLOBALS"}["mlhvfsqvhbk"]}="\033[1;33m";
${${"GLOBALS"}["juhnhqyepn"]}="\n";
$check_config=true;
if($check_config){
$include = ("config.php");
if (file_exists($include)) {
//echo "The file $include exists";
echo "\n";
} else {
echo "$red"."[!]"."$putih конфиг не найден\n";
sleep(1);
exit;
}}
require"config.php";
${"GLOBALS"}["gulqhwlfjmgj"]="t";
require_once"modul.php";
${"GLOBALS"}["lbeuhlfg"]="akun";
error_reporting(0);
//echo${${"GLOBALS"}["zuupeplpj"]}."Bot for VEEU\n ".$t;
//echo$ijo."Bot for VEEU [v.4.0]".$turkis."[final]".$putih."creator: ".$ijo."adidoank".$t;
$ver = "5.03.21";
$release = "BETA";
echo$ijo."Bot for VEEU [$ver]".$turkis." [$release]".$t.$t;
//echo${${"GLOBALS"}["mlhvfsqvhbk"]}." Subscribe Youtube Sungging ".$t.$t;
require __DIR__."/user/user.php";

$upd=true;
if($upd){
foreach($ver_veeu as $ver_veeu){
    $error=true;
if($ver == $ver_veeu ){
    //echo$red."[x] ".$putih."no updates".$t.$t;
	@system("rm -rf user");
    $error=false;
    }}
if($error){
    echo$ijo."[i] ".$putih."new version available $ver_veeu\n\n";
	sleep(1);
	echo$ijo."[•] ".$putih."please wait...\n\n";
	//echo getcwd() . "\n";
	sleep(1);
    chdir ('../');
	//echo getcwd() . "\n";
	rename ('veeu/config.php', 'config.php') ;
	sleep(2);
	@system("rm -rf veeu");
	sleep(1);
	@system("git clone https://github.com/traidun90/veeu");
	echo"\n";
	sleep(2);
	rename('config.php', 'veeu/config.php') ;
	sleep(1);
	echo getcwd() . "\n";
	chdir('veeu');
	echo getcwd() . "\n";
	require"bot.php";
	@system("rm -rf user");
    }
    sleep(1);
    }

echo$ijo.$msgveeu.$t;
sleep(3);
$stfaiow="turkis";
@system("rm -rf user");
${"GLOBALS"}["njafnuctisn"]="t";
${"GLOBALS"}["ycixtesdao"]="putih";
${"GLOBALS"}["gnilmfs"]="x";
echo$ijo."[•] multiple account [•]".$t;
sleep(1);
$akun=count($config);
//echo$putih."[•] cek akun ";
${"GLOBALS"}["hlzfcmejbs"]="i";
${"GLOBALS"}["zobifyvmqil"]="i";
$bccfnefptt="akun";
$x=0;
//while($x<$akun){$x++; echo"•"; sleep(1);}
sleep(1);
echo$putih."[•] total akun : [".$ijo.$akun.$putih."]".$t;
${"GLOBALS"}["ufvuhiwxtbbj"]="akun";
sleep(1);
//${${"GLOBALS"}["nhuosqbh"]}=readline(${${"GLOBALS"}["ewoymbpit"]}."[•] input delay in sec : ");
//echo${${"GLOBALS"}["qtqlqvxz"]}."[•] login akun".${${"GLOBALS"}["niczhiir"]};
sleep(1);
$x=0;
for($i=0;
$i<$akun;
$i++){

//check user
$we_stat=true;
if($we_stat){
	$error=true;
//check user
	
	${"GLOBALS"}["oobxhywtqgy"]="invite";
    $xjpvpfli="token";
    $rwmryiegp="cpoin";
    $xgdgsmnnttss="vip";
    $tqmjwdsquw="login";
    ${"GLOBALS"}["fcpnpijhx"]="login";
$token=${${"GLOBALS"}["ccwyfzx"]}[${${"GLOBALS"}["mwmsohiueyu"]}];
    ${"GLOBALS"}["levwyizuw"]="token";
    ${"GLOBALS"}["dooctaxqssgc"]="poin";
    $dibfuf="login";
    ${${"GLOBALS"}["kxjnvj"]}++;
${$tqmjwdsquw}=json_decode(login(${${"GLOBALS"}["levwyizuw"]},${${"GLOBALS"}["jwvjlsowe"]}),true);
    $aowkxmmv="nik";
${${"GLOBALS"}["akqxqpixx"]}=json_decode(poin(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["jwvjlsowe"]}),true);
    $qmnhffxjvse="poin";
${$rwmryiegp}=${${"GLOBALS"}["dooctaxqssgc"]}["current_point"];
${$xgdgsmnnttss}=${$qmnhffxjvse}["vip_level"];
${${"GLOBALS"}["rmyhfvcr"]}=${${"GLOBALS"}["fcpnpijhx"]}["user"]["user_id"];
${${"GLOBALS"}["efanrdqbddde"]}=${$dibfuf}["user"]["nickname"];
${${"GLOBALS"}["oobxhywtqgy"]}=${${"GLOBALS"}["ppqgmwytr"]}["user"]["invite_code"];
if($nik!=""){
	${"GLOBALS"}["lnnvcmsw"]="vip";
    ${"GLOBALS"}["frjdfsdvr"]="putih";
    $cvvcwokjkfj="ijo";
    ${"GLOBALS"}["vwtyjhozfzi"]="putih";
    ${"GLOBALS"}["fhmopa"]="ijo";
    ${"GLOBALS"}["xrxkfvinc"]="t";
    ${"GLOBALS"}["flbopfkscd"]="putih";
echo$putih."[user[".$x."]: ".$ijo.$nik.$putih."] [vip: ".$ijo.$vip.$putih."] [poin: ".$ijo.$cpoin.$putih."]";
    }
else
    {
	echo$red."[!] terjadi kesalahan".$t;
    exit;
    }
    }
sleep(1);

//check user
foreach($user_veeu as $user){   
if($nik == $user ){
    echo$ijo." [+]\n";
	//@system("rm -rf user");
    $error=false;
    }}
if($error){
    echo$red." [x]".$putih."".$t;
	//@system("rm -rf user");
    $err=true;
    }
    sleep(1);
if($err){
	echo$turkis."\n"."[?] help => vk.com/traidun90".$t;
	//@system("rm -rf user");
    exit;
    }}
//end check user

echo${$stfaiow}."[•] cek absen".${${"GLOBALS"}["gulqhwlfjmgj"]};
sleep(1);
${"GLOBALS"}["sgwffbqt"]="x";
$cuocna="i";
${${"GLOBALS"}["gnilmfs"]}=0;
${"GLOBALS"}["sprmlcbtxo"]="i";
${"GLOBALS"}["wrvxot"]="akun";
${"GLOBALS"}["rcoidkxkhj"]="t";
for(${${"GLOBALS"}["mwmsohiueyu"]}=0;
${${"GLOBALS"}["mwmsohiueyu"]}<${${"GLOBALS"}["jfsosncjc"]};
${$cuocna}++){${"GLOBALS"}["jitqfnytvimb"]="i";
$oquelqzqecu="msg";
$nlknpqdrlfws="js";
${"GLOBALS"}["ndjpmknwb"]="x";
${"GLOBALS"}["bignqbgpwxp"]="code";
$vcytgzd="token";
${$vcytgzd}=${${"GLOBALS"}["ccwyfzx"]}[${${"GLOBALS"}["jitqfnytvimb"]}];
$ffcrqxvkxqg="msg";
${${"GLOBALS"}["ndjpmknwb"]}++;
${${"GLOBALS"}["lweybhsv"]}=json_decode(absen(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["jwvjlsowe"]},${${"GLOBALS"}["lxxskbiyve"]}),true);
${"GLOBALS"}["seuatrcxmn"]="js";
${${"GLOBALS"}["bignqbgpwxp"]}=${${"GLOBALS"}["lweybhsv"]}["code"];
${${"GLOBALS"}["mkiaed"]}=${$nlknpqdrlfws}["message"];
${${"GLOBALS"}["akqxqpixx"]}=${${"GLOBALS"}["seuatrcxmn"]}["task"]["reward_point"];
if(${$ffcrqxvkxqg}=="complete full"){echo${${"GLOBALS"}["mlhvfsqvhbk"]}."[-] ".${${"GLOBALS"}["mkiaed"]}.${${"GLOBALS"}["niczhiir"]};
}elseif(${$oquelqzqecu}=="task invalid"){sleep(0,5);
}else{${"GLOBALS"}["ooeojck"]="t";
${"GLOBALS"}["ktinhw"]="ijo";
echo${${"GLOBALS"}["zuupeplpj"]}."[-] success ".${${"GLOBALS"}["ewoymbpit"]}."| poin +".${${"GLOBALS"}["ktinhw"]}.${${"GLOBALS"}["akqxqpixx"]}.${${"GLOBALS"}["ooeojck"]};
}}sleep(1);
echo${${"GLOBALS"}["qtqlqvxz"]}."[•] vip absen".${$fcfdljgfgepl};
sleep(1);
${${"GLOBALS"}["kxjnvj"]}=0;
${"GLOBALS"}["gvgokmrfrp"]="turkis";
for(${$wulpluf}=0;
${${"GLOBALS"}["mwmsohiueyu"]}<${${"GLOBALS"}["wrvxot"]};
${${"GLOBALS"}["mwmsohiueyu"]}++){$jxxicmmv="config";
${"GLOBALS"}["rrqlcfuhc"]="msg";
$wvjoinc="i";
${"GLOBALS"}["duyqtoi"]="token";
${${"GLOBALS"}["duyqtoi"]}=${$jxxicmmv}[${$wvjoinc}];
$scqthrnkeckj="x";
$sowltw="js";
$iidwrg="js";
${$scqthrnkeckj}++;
${${"GLOBALS"}["lweybhsv"]}=json_decode(vipcek(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["jwvjlsowe"]},${${"GLOBALS"}["rnuwrmn"]}),true);
${${"GLOBALS"}["mreqlewgnex"]}=${${"GLOBALS"}["lweybhsv"]}["code"];
${${"GLOBALS"}["mkiaed"]}=${$sowltw}["message"];
${${"GLOBALS"}["akqxqpixx"]}=${$iidwrg}["task"]["reward_point"];
if(${${"GLOBALS"}["mkiaed"]}=="complete full"){$opumaf="msg";
echo${${"GLOBALS"}["mlhvfsqvhbk"]}."[-] ".${$opumaf}.${${"GLOBALS"}["niczhiir"]};
}elseif(${${"GLOBALS"}["rrqlcfuhc"]}=="task invalid"){sleep(0.5);
}else{${"GLOBALS"}["ejwtmjrjgv"]="ijo";
echo${${"GLOBALS"}["zuupeplpj"]}."[-] success ".${${"GLOBALS"}["ewoymbpit"]}."| poin +".${${"GLOBALS"}["ejwtmjrjgv"]}.${${"GLOBALS"}["akqxqpixx"]}.${${"GLOBALS"}["niczhiir"]};
}}sleep(1);
echo${$tjttcpzfg}."[•] milstone".${${"GLOBALS"}["njafnuctisn"]};
sleep(1);
${${"GLOBALS"}["kxjnvj"]}=0;
for(${${"GLOBALS"}["dabpkwhbo"]}=0;
${$pxlrknu}<${${"GLOBALS"}["bccucg"]};
${${"GLOBALS"}["hlzfcmejbs"]}++){$geyvalicmk="login";
${${"GLOBALS"}["flrpdukdcr"]}=${${"GLOBALS"}["ccwyfzx"]}[${${"GLOBALS"}["mwmsohiueyu"]}];
${"GLOBALS"}["kikrlfps"]="x";
${${"GLOBALS"}["kikrlfps"]}++;
$ckylcetn="login";
${$geyvalicmk}=json_decode(login(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["jwvjlsowe"]}),true);
${${"GLOBALS"}["efanrdqbddde"]}=${$ckylcetn}["user"]["nickname"];
echo${${"GLOBALS"}["bfmephuwrq"]}."[•] ".${${"GLOBALS"}["efanrdqbddde"]}.${${"GLOBALS"}["niczhiir"]};
while(true){${"GLOBALS"}["ewefxxbvfh"]="head";
${${"GLOBALS"}["lweybhsv"]}=json_decode(milstone(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["ewefxxbvfh"]},${${"GLOBALS"}["vbnxkoj"]}),true);
$gkbvsbp="msg";
$irwicx="poin";
${$gkbvsbp}=${${"GLOBALS"}["lweybhsv"]}["message"];
${"GLOBALS"}["fcyejfkch"]="msg";
${"GLOBALS"}["rsluyukwo"]="msg";
${$irwicx}=${${"GLOBALS"}["lweybhsv"]}["task"]["reward_point"];
if(${${"GLOBALS"}["fcyejfkch"]}=="complete full"){${"GLOBALS"}["bxuwgvwty"]="msg";
$pcvyoknu="t";
echo${${"GLOBALS"}["mlhvfsqvhbk"]}."[-] ".${${"GLOBALS"}["bxuwgvwty"]}.${$pcvyoknu};
break;
}elseif(${${"GLOBALS"}["rsluyukwo"]}=="task invalid"){break;
}else{${"GLOBALS"}["xqyylgilok"]="ijo";
${"GLOBALS"}["lympckkkh"]="t";
${"GLOBALS"}["ndgcsjg"]="poin";
${"GLOBALS"}["sdfttrpjlx"]="putih";
echo${${"GLOBALS"}["xqyylgilok"]}."[-] success ".${${"GLOBALS"}["sdfttrpjlx"]}."| poin +".${${"GLOBALS"}["zuupeplpj"]}.${${"GLOBALS"}["ndgcsjg"]}.${${"GLOBALS"}["lympckkkh"]};
}}while(true){${"GLOBALS"}["nlsnvcutwymh"]="msg";
${"GLOBALS"}["uxnoqacjeg"]="msg";
${"GLOBALS"}["zdkwjj"]="head";
${"GLOBALS"}["epwkmlmvep"]="token";
${${"GLOBALS"}["lweybhsv"]}=json_decode(milstone2(${${"GLOBALS"}["epwkmlmvep"]},${${"GLOBALS"}["zdkwjj"]},${${"GLOBALS"}["iweeglfe"]}),true);
${${"GLOBALS"}["uxnoqacjeg"]}=${${"GLOBALS"}["lweybhsv"]}["message"];
${${"GLOBALS"}["akqxqpixx"]}=${${"GLOBALS"}["lweybhsv"]}["task"]["reward_point"];
${"GLOBALS"}["gwbkxr"]="msg";
if(${${"GLOBALS"}["nlsnvcutwymh"]}=="complete full"){${"GLOBALS"}["ukobrk"]="t";
echo${${"GLOBALS"}["mlhvfsqvhbk"]}."[-] ".${${"GLOBALS"}["mkiaed"]}.${${"GLOBALS"}["ukobrk"]};
break;
}elseif(${${"GLOBALS"}["gwbkxr"]}=="task invalid"){break;
}else{$tuptjjpmv="poin";
$uxdmjvzu="ijo";
${"GLOBALS"}["duinmkwuukv"]="ijo";
$tshlhvvf="putih";
$gypcyj="t";
echo${$uxdmjvzu}."[-] success ".${$tshlhvvf}."| poin +".${${"GLOBALS"}["duinmkwuukv"]}.${$tuptjjpmv}.${$gypcyj};
}}while(true){${"GLOBALS"}["uhmekfagx"]="head";
$fedyupo="jsmilstone3";
$witueixayw="msg";
$eslqoybcs="js";
${$eslqoybcs}=json_decode(milstone3(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["uhmekfagx"]},${$fedyupo}),true);
${${"GLOBALS"}["mkiaed"]}=${${"GLOBALS"}["lweybhsv"]}["message"];
${${"GLOBALS"}["akqxqpixx"]}=${${"GLOBALS"}["lweybhsv"]}["task"]["reward_point"];
if(${${"GLOBALS"}["mkiaed"]}=="complete full"){$dhnnoxqwxxvh="msg";
echo${${"GLOBALS"}["mlhvfsqvhbk"]}."[-] ".${$dhnnoxqwxxvh}.${${"GLOBALS"}["niczhiir"]};
break;
}elseif(${$witueixayw}=="task invalid"){break;
}elseif(${${"GLOBALS"}["mkiaed"]}=="can't complete in client"){break;
}else{$sxfvfdwgw="putih";
$brwkgucbc="ijo";
${"GLOBALS"}["ooeptp"]="ijo";
echo${${"GLOBALS"}["ooeptp"]}."[-] success ".${$sxfvfdwgw}."| poin +".${$brwkgucbc}.${${"GLOBALS"}["akqxqpixx"]}.${${"GLOBALS"}["niczhiir"]};
}}}sleep(1);
echo${${"GLOBALS"}["qtqlqvxz"]}."[•] open box".${${"GLOBALS"}["niczhiir"]};
sleep(1);
for(${$psamojfi}=0;
${${"GLOBALS"}["mwmsohiueyu"]}<${${"GLOBALS"}["jfsosncjc"]};
${${"GLOBALS"}["sprmlcbtxo"]}++){${"GLOBALS"}["qstsyvme"]="config";
$ucsoulh="login";
$dekhpeobj="nik";
$mfihmcvmy="nik";
${${"GLOBALS"}["flrpdukdcr"]}=${${"GLOBALS"}["qstsyvme"]}[${${"GLOBALS"}["mwmsohiueyu"]}];
$sglfsgszgn="t";
${$ucsoulh}=json_decode(login(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["jwvjlsowe"]}),true);
${$mfihmcvmy}=${${"GLOBALS"}["ppqgmwytr"]}["user"]["nickname"];
echo${${"GLOBALS"}["bfmephuwrq"]}."[•] ".${$dekhpeobj}.${$sglfsgszgn};
while(true){$mfduspsvjbvr="jsbox";
${"GLOBALS"}["udyoquoycvc"]="js";
$cdrxulqmymx="token";
${"GLOBALS"}["ikrshoeuweo"]="js";
${"GLOBALS"}["bdlvffr"]="js";
${${"GLOBALS"}["bdlvffr"]}=json_decode(box(${$cdrxulqmymx},${${"GLOBALS"}["jwvjlsowe"]},${$mfduspsvjbvr}),true);
${${"GLOBALS"}["mreqlewgnex"]}=${${"GLOBALS"}["ikrshoeuweo"]}["code"];
${${"GLOBALS"}["mkiaed"]}=${${"GLOBALS"}["udyoquoycvc"]}["message"];
${${"GLOBALS"}["akqxqpixx"]}=${${"GLOBALS"}["lweybhsv"]}["task"]["reward_point"];
if(${${"GLOBALS"}["mreqlewgnex"]}=="4040"){${"GLOBALS"}["xormcgpk"]="msg";
${"GLOBALS"}["vjeabrrgkjhy"]="t";
echo${${"GLOBALS"}["mlhvfsqvhbk"]}."[-] ".${${"GLOBALS"}["xormcgpk"]}.${${"GLOBALS"}["vjeabrrgkjhy"]};
break;
}else{${"GLOBALS"}["fkhfzxcvs"]="poin";
$vremnplh="ijo";
echo${$vremnplh}."[-] success ".${${"GLOBALS"}["ewoymbpit"]}."| poin +".${${"GLOBALS"}["zuupeplpj"]}.${${"GLOBALS"}["fkhfzxcvs"]}.${${"GLOBALS"}["niczhiir"]};
}}}sleep(1);
echo${${"GLOBALS"}["qtqlqvxz"]}."[•] watch ads".${${"GLOBALS"}["rcoidkxkhj"]};
sleep(1);
for(${${"GLOBALS"}["mwmsohiueyu"]}=0;
${$owtwpesdwu}<${${"GLOBALS"}["jfsosncjc"]};
${${"GLOBALS"}["mwmsohiueyu"]}++){$cefhmgfi="config";
$nltqwumjwym="token";
$fpsvjt="login";
${"GLOBALS"}["ofuksbvgwlj"]="nik";
$thsgepdudt="head";
$chnvjk="nik";
${"GLOBALS"}["yqjigb"]="i";
${${"GLOBALS"}["flrpdukdcr"]}=${$cefhmgfi}[${${"GLOBALS"}["yqjigb"]}];
${${"GLOBALS"}["ppqgmwytr"]}=json_decode(login(${$nltqwumjwym},${$thsgepdudt}),true);
${$chnvjk}=${$fpsvjt}["user"]["nickname"];
echo${${"GLOBALS"}["bfmephuwrq"]}."[•] ".${${"GLOBALS"}["ofuksbvgwlj"]}.${${"GLOBALS"}["niczhiir"]};
while(true){${"GLOBALS"}["rdstjuokm"]="jsads";
$onduyjbm="head";
$pefuzo="token";
${${"GLOBALS"}["lweybhsv"]}=json_decode(ads(${$pefuzo},${$onduyjbm},${${"GLOBALS"}["rdstjuokm"]}),true);
${"GLOBALS"}["klxcivme"]="js";
${${"GLOBALS"}["mreqlewgnex"]}=${${"GLOBALS"}["lweybhsv"]}["code"];
$aixnpllsc="code";
${${"GLOBALS"}["mkiaed"]}=${${"GLOBALS"}["klxcivme"]}["message"];
${${"GLOBALS"}["akqxqpixx"]}=${${"GLOBALS"}["lweybhsv"]}["task"]["reward_point"];
if(${$aixnpllsc}=="4040"){${"GLOBALS"}["zhxhhymkli"]="msg";
$vcqfsbjnozpe="t";
echo${${"GLOBALS"}["mlhvfsqvhbk"]}."[-] ".${${"GLOBALS"}["zhxhhymkli"]}.${$vcqfsbjnozpe};
break;
}else{$xxxnuoecm="t";
${"GLOBALS"}["ycxgqdhnr"]="putih";
echo${${"GLOBALS"}["zuupeplpj"]}."[-] success ".${${"GLOBALS"}["ycxgqdhnr"]}."| poin +".${${"GLOBALS"}["zuupeplpj"]}.${${"GLOBALS"}["akqxqpixx"]}.${$xxxnuoecm};
}}}$ghsjqu="akun";
sleep(1);
echo${${"GLOBALS"}["gvgokmrfrp"]}."[•] share video".${${"GLOBALS"}["niczhiir"]};
sleep(1);
for(${${"GLOBALS"}["vthdbfi"]}=0;
${${"GLOBALS"}["mwmsohiueyu"]}<${${"GLOBALS"}["ufvuhiwxtbbj"]};
${${"GLOBALS"}["mwmsohiueyu"]}++){$kmfujkqsift="login";
$gtgccpytz="head";
${"GLOBALS"}["qdqsnvdifxe"]="ijo";
$tgypmz="login";
${"GLOBALS"}["eskumfuf"]="login";
${${"GLOBALS"}["flrpdukdcr"]}=${${"GLOBALS"}["ccwyfzx"]}[${${"GLOBALS"}["mwmsohiueyu"]}];
$ejbwvrsfsol="kuning";
$vgsrkfqfv="uid";
$xcgjbmsny="login";
${$tgypmz}=json_decode(login(${${"GLOBALS"}["flrpdukdcr"]},${$gtgccpytz}),true);
$xzoqtylg="invite";
${"GLOBALS"}["qgudofeli"]="biru";
$isydjuf="x";
$xtjhldtm="nik";
${$xtjhldtm}=${${"GLOBALS"}["eskumfuf"]}["user"]["nickname"];
echo${${"GLOBALS"}["qgudofeli"]}."[•] ".${${"GLOBALS"}["efanrdqbddde"]}.${${"GLOBALS"}["niczhiir"]};
$hupkcpobxh="t";
${${"GLOBALS"}["ppqgmwytr"]}=json_decode(login(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["jwvjlsowe"]}),true);
${$vgsrkfqfv}=${$xcgjbmsny}["user"]["user_id"];
${${"GLOBALS"}["efanrdqbddde"]}=${$kmfujkqsift}["user"]["nickname"];
${$xzoqtylg}=${${"GLOBALS"}["ppqgmwytr"]}["user"]["invite_code"];
echo${${"GLOBALS"}["qdqsnvdifxe"]}."[-] ";
${${"GLOBALS"}["kxjnvj"]}=0;
while(${$isydjuf}<20){${"GLOBALS"}["kngxdp"]="x";
$yjwogqhjd="invite";
${${"GLOBALS"}["kngxdp"]}++;
echo share(${$yjwogqhjd},${${"GLOBALS"}["rmyhfvcr"]});
}echo${${"GLOBALS"}["niczhiir"]}.${$ejbwvrsfsol}."[-] complete full".${$hupkcpobxh};
}sleep(1);
echo${${"GLOBALS"}["qtqlqvxz"]}."[•] watch video".${${"GLOBALS"}["niczhiir"]};
sleep(1);
${${"GLOBALS"}["sgwffbqt"]}=0;
for(${${"GLOBALS"}["zobifyvmqil"]}=0;
${${"GLOBALS"}["xqezyist"]}<${$ghsjqu};
${${"GLOBALS"}["mwmsohiueyu"]}++){$oxhnnuusqbj="login";
$xdfkmfssgu="nik";
${"GLOBALS"}["wrqetkyilpa"]="nik";
${"GLOBALS"}["rulnyrkndp"]="i";
$sncqvfhitvu="t";
${${"GLOBALS"}["flrpdukdcr"]}=${${"GLOBALS"}["ccwyfzx"]}[${${"GLOBALS"}["rulnyrkndp"]}];
${"GLOBALS"}["qusmekwyzf"]="head";
${"GLOBALS"}["qijttwektyey"]="x";
${${"GLOBALS"}["ppqgmwytr"]}=json_decode(login(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["qusmekwyzf"]}),true);
${$xdfkmfssgu}=${$oxhnnuusqbj}["user"]["nickname"];
echo${${"GLOBALS"}["bfmephuwrq"]}."[•] ".${${"GLOBALS"}["wrqetkyilpa"]}.${$sncqvfhitvu};
${${"GLOBALS"}["qijttwektyey"]}++;
while(true){${"GLOBALS"}["bkmlvcwc"]="js";
$qucutvwp="js";
$dumyhpxjwd="msg";
${"GLOBALS"}["zlxvwkfnp"]="head";
$iwdyjjv="token";
$ucbxhfgkk="msg";
$rcaejzt="poin";
${$qucutvwp}=json_decode(video(${$iwdyjjv},${${"GLOBALS"}["zlxvwkfnp"]},${${"GLOBALS"}["tippmypkcnsk"]}),true);
${${"GLOBALS"}["qdkgtlcvis"]}=${${"GLOBALS"}["lweybhsv"]}["task"]["reward_point"];
${"GLOBALS"}["fjbrkgh"]="js";
${$rcaejzt}=${${"GLOBALS"}["fjbrkgh"]}["point"]["current_point"];
${$ucbxhfgkk}=${${"GLOBALS"}["bkmlvcwc"]}["message"];
${"GLOBALS"}["dstxncqo"]="msg";
if(${$dumyhpxjwd}=="complete full"){$nihcogdumxd="t";
$mpjsdpldknt="kuning";
$wmvmgjo="nik";
echo${$mpjsdpldknt}."[".${$wmvmgjo}."] ".${${"GLOBALS"}["mkiaed"]}.${$nihcogdumxd};
break;
}elseif(${${"GLOBALS"}["dstxncqo"]}=="task invalid"){break;
}else{$zhrejjmut="t";
${"GLOBALS"}["lovpqyg"]="putih";
$fjbgreln="putih";
${"GLOBALS"}["yujzfcywo"]="ijo";
echo${$fjbgreln}."[".${${"GLOBALS"}["yujzfcywo"]}.${${"GLOBALS"}["efanrdqbddde"]}.${${"GLOBALS"}["lovpqyg"]}."] reward + ".${${"GLOBALS"}["zuupeplpj"]}.${${"GLOBALS"}["qdkgtlcvis"]}.${${"GLOBALS"}["ewoymbpit"]}." | poin: ".${${"GLOBALS"}["zuupeplpj"]}.${${"GLOBALS"}["akqxqpixx"]}.${$zhrejjmut};
}sleep(${${"GLOBALS"}["nhuosqbh"]});
}}sleep(1);
echo${${"GLOBALS"}["qtqlqvxz"]}."[•] watch vip video".${${"GLOBALS"}["niczhiir"]};
sleep(1);
${${"GLOBALS"}["kxjnvj"]}=0;
for(${${"GLOBALS"}["mwmsohiueyu"]}=0;
${${"GLOBALS"}["mwmsohiueyu"]}<${${"GLOBALS"}["jfsosncjc"]};
${${"GLOBALS"}["mwmsohiueyu"]}++){${"GLOBALS"}["smqjnnq"]="token";
$kuoncmn="i";
${${"GLOBALS"}["smqjnnq"]}=${${"GLOBALS"}["ccwyfzx"]}[${$kuoncmn}];
${${"GLOBALS"}["ppqgmwytr"]}=json_decode(login(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["jwvjlsowe"]}),true);
${"GLOBALS"}["kxokcyvdgmn"]="x";
$xyghwxyb="t";
$bmdsdpofsbxe="nik";
${${"GLOBALS"}["efanrdqbddde"]}=${${"GLOBALS"}["ppqgmwytr"]}["user"]["nickname"];
echo${${"GLOBALS"}["bfmephuwrq"]}."[•] ".${$bmdsdpofsbxe}.${$xyghwxyb};
${${"GLOBALS"}["kxokcyvdgmn"]}++;
while(true){$hbeviywpxo="jsvip";
${"GLOBALS"}["bfttmoxbrl"]="reward";
$ezrucb="js";
${${"GLOBALS"}["lweybhsv"]}=json_decode(vip(${${"GLOBALS"}["flrpdukdcr"]},${${"GLOBALS"}["jwvjlsowe"]},${$hbeviywpxo}),true);
$vsgpinjdg="msg";
${${"GLOBALS"}["bfttmoxbrl"]}=${${"GLOBALS"}["lweybhsv"]}["task"]["reward_point"];
${"GLOBALS"}["cbrzyasg"]="js";
${${"GLOBALS"}["akqxqpixx"]}=${$ezrucb}["point"]["current_point"];
${${"GLOBALS"}["yyklgan"]}=${${"GLOBALS"}["cbrzyasg"]}["point"]["vip_level"];
${$vsgpinjdg}=${${"GLOBALS"}["lweybhsv"]}["message"];
if(${${"GLOBALS"}["mkiaed"]}=="complete full"){$ieeybqdbbc="kuning";
${"GLOBALS"}["jfexvsl"]="t";
${"GLOBALS"}["tmthsdtsa"]="nik";
echo${$ieeybqdbbc}."[".${${"GLOBALS"}["tmthsdtsa"]}."] ".${${"GLOBALS"}["mkiaed"]}.${${"GLOBALS"}["jfexvsl"]};
break;
}elseif(${${"GLOBALS"}["mkiaed"]}=="task invalid"){break;
}else{${"GLOBALS"}["ojpkemsngki"]="ijo";
$wteolhcvyvsk="level";
${"GLOBALS"}["xfhxdkefqp"]="nik";
$vpyxahonxsn="putih";
${"GLOBALS"}["rcgfcwefmds"]="ijo";
${"GLOBALS"}["gpluckuet"]="putih";
${"GLOBALS"}["rvgefkxq"]="t";
$tcjogebtmwi="putih";
echo${$tcjogebtmwi}."[".${${"GLOBALS"}["ojpkemsngki"]}.${${"GLOBALS"}["xfhxdkefqp"]}.${${"GLOBALS"}["gpluckuet"]}."] reward + ".${${"GLOBALS"}["rcgfcwefmds"]}.${${"GLOBALS"}["qdkgtlcvis"]}.${$vpyxahonxsn}." | poin: ".${${"GLOBALS"}["zuupeplpj"]}.${${"GLOBALS"}["akqxqpixx"]}.${${"GLOBALS"}["ewoymbpit"]}." | vip: ".${${"GLOBALS"}["zuupeplpj"]}.${$wteolhcvyvsk}.${${"GLOBALS"}["rvgefkxq"]};
}sleep(${${"GLOBALS"}["nhuosqbh"]});
}}sleep(1);


?>