<?php 
${"GLOBALS"}["xrmomfc"]="code";
${"GLOBALS"}["uclcsqtu"]="info";
${"GLOBALS"}["hrzorwboage"]="jsbox";
${"GLOBALS"}["vlluviu"]="jsmilstone";
${"GLOBALS"}["plsneehscks"]="token";
${"GLOBALS"}["lxjeigd"]="vipcekin";
${"GLOBALS"}["dayrirh"]="jsabsen";
${"GLOBALS"}["ckvohvqnosuf"]="head";
${"GLOBALS"}["iehpsltfr"]="result";
${"GLOBALS"}["iqnquznevdmq"]="curl";
${"GLOBALS"}["cdhcqerxz"]="jsads";
${"GLOBALS"}["ycotgfkp"]="ads";
${"GLOBALS"}["olfzufxjpqzl"]="jsvip";
$ptxgdet="vip";
${"GLOBALS"}["xbwsneul"]="video";
${"GLOBALS"}["moechysaqo"]="jsmilstone3";
${"GLOBALS"}["uhtuwj"]="milstone3";
${"GLOBALS"}["jnnfph"]="jsmilstone2";
${"GLOBALS"}["ppdmbigihgk"]="milstone2";
${"GLOBALS"}["ejimccrhlt"]="milstone";
${"GLOBALS"}["qmpkvkrpyua"]="cekin";
${"GLOBALS"}["ubnkrvfpbrqc"]="head";
${${"GLOBALS"}["ubnkrvfpbrqc"]}[]="Host: www.veeuapp.com";
${"GLOBALS"}["vqmrchnxk"]="vipcekin";
${"GLOBALS"}["akduuq"]="jsvideo";
$posuiporjhp="absen";
${"GLOBALS"}["fceqmct"]="absen";
"Connection: Keep-Alive";
$biqtsoixfnh="jsmilstone";
$hyrezcu="jsabsen";
"Accept-Encoding: gzip";
"User-Agent: okhttp/3.10.0";
${$posuiporjhp}=array("locale"=>"in_ID","task_extra_info"=>"","task_name"=>"daily_checkin_01","timezone"=>"GMT+07:00");
$vdiootjjxvd="milstone";
${$hyrezcu}=json_encode(${${"GLOBALS"}["fceqmct"]},true);
$qlsqhfoi="cekin";
${$qlsqhfoi}=array("locale"=>"in_ID","task_extra_info"=>"","task_name"=>"vip_checkin_01","timezone"=>"GMT+07:00");
${${"GLOBALS"}["vqmrchnxk"]}=json_encode(${${"GLOBALS"}["qmpkvkrpyua"]},true);
${"GLOBALS"}["wcqbcpskysd"]="vip";
$pptbyft="box";
${${"GLOBALS"}["ejimccrhlt"]}=array("latitude"=>"-6.885519","locale"=>"in_ID","longitude"=>"107.6228","task_extra_info"=>"","task_name"=>"vip_reward_01","timezone"=>"GMT+07:00");
${$biqtsoixfnh}=json_encode(${$vdiootjjxvd},true);
$obofjcme="box";
${${"GLOBALS"}["ppdmbigihgk"]}=array("latitude"=>"-6.885519","locale"=>"in_ID","longitude"=>"107.6228","task_extra_info"=>"","task_name"=>"vip_milestone_01","timezone"=>"GMT+07:00");
$nyaqfyivts="jsbox";
${${"GLOBALS"}["jnnfph"]}=json_encode(${${"GLOBALS"}["ppdmbigihgk"]},true);
${${"GLOBALS"}["uhtuwj"]}=array("latitude"=>"-6.885519","locale"=>"in_ID","longitude"=>"107.6228","task_extra_info"=>"","task_name"=>"vip_server_milestone_01","timezone"=>"GMT+07:00");
${${"GLOBALS"}["moechysaqo"]}=json_encode(${${"GLOBALS"}["uhtuwj"]},true);
${$obofjcme}=array("latitude"=>"-6.885519","locale"=>"in_ID","longitude"=>"107.6228","task_extra_info"=>"","task_name"=>"treasure_box_01","timezone"=>"GMT+07:00");
${$nyaqfyivts}=json_encode(${$pptbyft},true);
${${"GLOBALS"}["xbwsneul"]}=array("locale"=>"in_ID","task_extra_info"=>"","task_name"=>"watch_video_ball_01","timezone"=>"GMT+07:00");
${${"GLOBALS"}["akduuq"]}=json_encode(${${"GLOBALS"}["xbwsneul"]},true);
${${"GLOBALS"}["wcqbcpskysd"]}=["locale"=>"in_ID","task_extra_info"=>"","task_name"=>"vip_watch_video_ball_01","timezone"=>"GMT+07:00"];
${${"GLOBALS"}["olfzufxjpqzl"]}=json_encode(${$ptxgdet},true);
${${"GLOBALS"}["ycotgfkp"]}=array("latitude"=>"-6.885519","locale"=>"in_ID","longitude"=>"107.6228","task_extra_info"=>"","task_name"=>"watch_ad_01","timezone"=>"GMT+07:00");
${${"GLOBALS"}["cdhcqerxz"]}=json_encode(${${"GLOBALS"}["ycotgfkp"]},true);
function login($token,$head){${${"GLOBALS"}["iqnquznevdmq"]}=curl_init();
$hwctfhc="token";
${"GLOBALS"}["flsijtoul"]="head";
${"GLOBALS"}["pvjelaxh"]="curl";
${"GLOBALS"}["ebqndsu"]="curl";
curl_setopt_array(${${"GLOBALS"}["pvjelaxh"]},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/me?access_token=".${$hwctfhc},CURLOPT_TIMEOUT=>30,CURLOPT_HTTPHEADER=>${${"GLOBALS"}["flsijtoul"]},CURLOPT_SSL_VERIFYPEER=>0,));
${${"GLOBALS"}["iehpsltfr"]}=curl_exec(${${"GLOBALS"}["ebqndsu"]});
curl_close(${${"GLOBALS"}["iqnquznevdmq"]});
return${${"GLOBALS"}["iehpsltfr"]};
}function poin($token,$head){${"GLOBALS"}["ciptppns"]="curl";
$dxiqvoegyzv="head";
$ovcdwwu="token";
${${"GLOBALS"}["ciptppns"]}=curl_init();
curl_setopt_array(${${"GLOBALS"}["iqnquznevdmq"]},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/incentive/point?access_token=".${$ovcdwwu}."&timezone=GMT%2B07%3A00&locale=in_ID",CURLOPT_TIMEOUT=>30,CURLOPT_HTTPHEADER=>${$dxiqvoegyzv},CURLOPT_SSL_VERIFYPEER=>0,));
${"GLOBALS"}["rffjpeo"]="result";
${${"GLOBALS"}["iehpsltfr"]}=curl_exec(${${"GLOBALS"}["iqnquznevdmq"]});
curl_close(${${"GLOBALS"}["iqnquznevdmq"]});
return${${"GLOBALS"}["rffjpeo"]};
}function absen($token,$head,$jsabsen){$ezinvgh="result";
${"GLOBALS"}["macwyhw"]="token";
$icfaymxbxr="result";
${"GLOBALS"}["nltpdkv"]="curl";
${${"GLOBALS"}["iqnquznevdmq"]}=curl_init();
curl_setopt_array(${${"GLOBALS"}["iqnquznevdmq"]},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/incentive/tasks?access_token=".${${"GLOBALS"}["macwyhw"]},CURLOPT_TIMEOUT=>30,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>${${"GLOBALS"}["ckvohvqnosuf"]},CURLOPT_POSTFIELDS=>${${"GLOBALS"}["dayrirh"]},CURLOPT_SSL_VERIFYPEER=>0,));
${$icfaymxbxr}=curl_exec(${${"GLOBALS"}["iqnquznevdmq"]});
curl_close(${${"GLOBALS"}["nltpdkv"]});
return${$ezinvgh};
}function vipcek($token,$head,$vipcekin){${${"GLOBALS"}["iqnquznevdmq"]}=curl_init();
$ebjfgeux="curl";
$ggvcfx="curl";
${"GLOBALS"}["mnxrynn"]="result";
$krqijkordtxn="token";
${"GLOBALS"}["kdgxvdtjjur"]="result";
curl_setopt_array(${$ggvcfx},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/incentive/tasks?access_token=".${$krqijkordtxn},CURLOPT_TIMEOUT=>30,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>${${"GLOBALS"}["ckvohvqnosuf"]},CURLOPT_POSTFIELDS=>${${"GLOBALS"}["lxjeigd"]},CURLOPT_SSL_VERIFYPEER=>0,));
${${"GLOBALS"}["kdgxvdtjjur"]}=curl_exec(${$ebjfgeux});
curl_close(${${"GLOBALS"}["iqnquznevdmq"]});
return${${"GLOBALS"}["mnxrynn"]};
}function milstone($token,$head,$jsmilstone){$uaecnckti="head";
${"GLOBALS"}["gydmfpea"]="result";
${"GLOBALS"}["fqdjpviu"]="curl";
$udjpeqrzdgio="curl";
${${"GLOBALS"}["fqdjpviu"]}=curl_init();
$xbmsbeitfnjr="curl";
curl_setopt_array(${$udjpeqrzdgio},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/incentive/tasks?access_token=".${${"GLOBALS"}["plsneehscks"]},CURLOPT_TIMEOUT=>30,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>${$uaecnckti},CURLOPT_POSTFIELDS=>${${"GLOBALS"}["vlluviu"]},CURLOPT_SSL_VERIFYPEER=>0,));
${${"GLOBALS"}["iehpsltfr"]}=curl_exec(${$xbmsbeitfnjr});
curl_close(${${"GLOBALS"}["iqnquznevdmq"]});
return${${"GLOBALS"}["gydmfpea"]};
}function milstone2($token,$head,$jsmilstone2){${"GLOBALS"}["gbogycvgp"]="curl";
${"GLOBALS"}["nnwcklmss"]="token";
${"GLOBALS"}["gpjyyadwkj"]="curl";
${${"GLOBALS"}["iqnquznevdmq"]}=curl_init();
curl_setopt_array(${${"GLOBALS"}["gbogycvgp"]},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/incentive/tasks?access_token=".${${"GLOBALS"}["nnwcklmss"]},CURLOPT_TIMEOUT=>30,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>${${"GLOBALS"}["ckvohvqnosuf"]},CURLOPT_POSTFIELDS=>${${"GLOBALS"}["jnnfph"]},CURLOPT_SSL_VERIFYPEER=>0,));
${${"GLOBALS"}["iehpsltfr"]}=curl_exec(${${"GLOBALS"}["gpjyyadwkj"]});
curl_close(${${"GLOBALS"}["iqnquznevdmq"]});
return${${"GLOBALS"}["iehpsltfr"]};
}function milstone3($token,$head,$jsmilstone3){${"GLOBALS"}["bmcmfesb"]="curl";
$jmhvoyj="jsmilstone3";
${${"GLOBALS"}["iqnquznevdmq"]}=curl_init();
curl_setopt_array(${${"GLOBALS"}["iqnquznevdmq"]},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/incentive/tasks?access_token=".${${"GLOBALS"}["plsneehscks"]},CURLOPT_TIMEOUT=>30,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>${${"GLOBALS"}["ckvohvqnosuf"]},CURLOPT_POSTFIELDS=>${$jmhvoyj},CURLOPT_SSL_VERIFYPEER=>0,));
${${"GLOBALS"}["iehpsltfr"]}=curl_exec(${${"GLOBALS"}["bmcmfesb"]});
curl_close(${${"GLOBALS"}["iqnquznevdmq"]});
return${${"GLOBALS"}["iehpsltfr"]};
}function box($token,$head,$jsbox){$dexwqfqnv="result";
$cdpjnkhhsd="curl";
${"GLOBALS"}["ajgfizkgu"]="curl";
$mgattddhexma="curl";
${${"GLOBALS"}["ajgfizkgu"]}=curl_init();
curl_setopt_array(${${"GLOBALS"}["iqnquznevdmq"]},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/incentive/tasks?access_token=".${${"GLOBALS"}["plsneehscks"]},CURLOPT_TIMEOUT=>30,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>${${"GLOBALS"}["ckvohvqnosuf"]},CURLOPT_POSTFIELDS=>${${"GLOBALS"}["hrzorwboage"]},CURLOPT_SSL_VERIFYPEER=>0,));
${$dexwqfqnv}=curl_exec(${$mgattddhexma});
curl_close(${$cdpjnkhhsd});
return${${"GLOBALS"}["iehpsltfr"]};
}function ads($token,$head,$jsads){$ozstqujsxl="curl";
$zppbxaii="curl";
$lqoioynrcl="head";
${$ozstqujsxl}=curl_init();
$fdbihfj="token";
curl_setopt_array(${${"GLOBALS"}["iqnquznevdmq"]},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/incentive/tasks?access_token=".${$fdbihfj},CURLOPT_TIMEOUT=>30,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>${$lqoioynrcl},CURLOPT_POSTFIELDS=>${${"GLOBALS"}["cdhcqerxz"]},CURLOPT_SSL_VERIFYPEER=>0,));
${${"GLOBALS"}["iehpsltfr"]}=curl_exec(${$zppbxaii});
curl_close(${${"GLOBALS"}["iqnquznevdmq"]});
return${${"GLOBALS"}["iehpsltfr"]};
}function share($invite,$uid){${"GLOBALS"}["dolgnus"]="curl";
$vytuestuppuk="curl";
${"GLOBALS"}["aptcrcx"]="info";
$ubdglbn="result";
$fppnqjdqs="invite";
$oawytsmvpm="uid";
${${"GLOBALS"}["iqnquznevdmq"]}=curl_init();
curl_setopt_array(${${"GLOBALS"}["dolgnus"]},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"http://www.veeuapp.com/page/share.html?doc_id=".rand(1000000000,9999999999)."&invite_code=".${$fppnqjdqs}."&flag=dividend&u=".${$oawytsmvpm}."&os=adr&sp=cp&ts=&d=5AFC6A4824045BD0E29B22D21F40E25F8F15544F",CURLOPT_TIMEOUT=>30,CURLOPT_SSL_VERIFYPEER=>0,));
${$ubdglbn}=curl_exec(${${"GLOBALS"}["iqnquznevdmq"]});
${${"GLOBALS"}["aptcrcx"]}=curl_getinfo(${${"GLOBALS"}["iqnquznevdmq"]});
curl_close(${$vytuestuppuk});
${"GLOBALS"}["hftscs"]="code";
${${"GLOBALS"}["hftscs"]}=${${"GLOBALS"}["uclcsqtu"]}["http_code"];
if(${${"GLOBALS"}["xrmomfc"]}=="200"){echo"•";
}else{echo"•";
}}function video($token,$head,$jsvideo){${"GLOBALS"}["whsvqq"]="jsvideo";
$kclbrtxjtf="curl";
${"GLOBALS"}["luqcaopzupbt"]="head";
${"GLOBALS"}["eheylpl"]="curl";
${"GLOBALS"}["ugecqfvve"]="token";
${${"GLOBALS"}["eheylpl"]}=curl_init();
curl_setopt_array(${${"GLOBALS"}["iqnquznevdmq"]},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/incentive/tasks?access_token=".${${"GLOBALS"}["ugecqfvve"]},CURLOPT_TIMEOUT=>30,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>${${"GLOBALS"}["luqcaopzupbt"]},CURLOPT_POSTFIELDS=>${${"GLOBALS"}["whsvqq"]},CURLOPT_SSL_VERIFYPEER=>0,));
${${"GLOBALS"}["iehpsltfr"]}=curl_exec(${$kclbrtxjtf});
curl_close(${${"GLOBALS"}["iqnquznevdmq"]});
return${${"GLOBALS"}["iehpsltfr"]};
}function vip($token,$head,$jsvip){${"GLOBALS"}["uzsmjv"]="result";
${${"GLOBALS"}["iqnquznevdmq"]}=curl_init();
curl_setopt_array(${${"GLOBALS"}["iqnquznevdmq"]},array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_URL=>"https://www.veeuapp.com/v1.0/incentive/tasks?access_token=".${${"GLOBALS"}["plsneehscks"]},CURLOPT_TIMEOUT=>30,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>${${"GLOBALS"}["ckvohvqnosuf"]},CURLOPT_POSTFIELDS=>${${"GLOBALS"}["olfzufxjpqzl"]},CURLOPT_SSL_VERIFYPEER=>0,));
${"GLOBALS"}["vscflibxuih"]="curl";
${"GLOBALS"}["zrducbhyxp"]="result";
${${"GLOBALS"}["uzsmjv"]}=curl_exec(${${"GLOBALS"}["iqnquznevdmq"]});
curl_close(${${"GLOBALS"}["vscflibxuih"]});
return${${"GLOBALS"}["zrducbhyxp"]};
}

?>
